import { Link } from 'react-router-dom';
import {
  ArrowUpRight,
  BarChart3,
  Megaphone,
  TrendingUp,
  Code2,
} from 'lucide-react';

const products = [
  {
    icon: BarChart3,
    name: 'Business Intelligence',
    tagline: 'All your data in one place',
    description:
      'A centralized dashboard that brings together sales, marketing, and operations — no more spreadsheet chaos.',
    href: '/products/business-intelligence',
    accent: 'from-brand/15 to-brand/0',
  },
  {
    icon: Megaphone,
    name: 'Ad Creation',
    tagline: 'AI-powered ads that convert',
    description:
      'Compelling ads generated by AI — targeted copy, sharp visuals, and platform-aware strategy.',
    href: '/products/ad-creation',
    accent: 'from-cream to-transparent',
  },
  {
    icon: TrendingUp,
    name: 'Investing App',
    tagline: 'Smarter investing, powered by AI',
    description:
      'Discover stocks, analyze trends, and get AI-driven insights — all in one clean app.',
    href: '/products/investing',
    accent: 'from-sky to-transparent',
  },
  {
    icon: Code2,
    name: 'App & Web Development',
    tagline: 'Digital products built to perform',
    description:
      'From concept to launch — we design and build websites and apps for businesses of every size.',
    href: '/products/development',
    accent: 'from-emerald-100 to-transparent',
  },
];

export default function ProductsGrid() {
  return (
    <section id="products" className="bg-white py-24 md:py-32">
      <div className="container-content">
        <div className="mx-auto max-w-2xl text-center">
          <span className="eyebrow">What we build</span>
          <h2 className="mt-5 font-heading text-4xl font-bold tracking-tight md:text-5xl">
            Four AI products. One company.
          </h2>
          <p className="mt-4 text-base leading-relaxed text-muted md:text-lg">
            Every product solves a real problem we&apos;ve seen businesses face.
            Built lean, designed clean, and delivered fast.
          </p>
        </div>

        <div className="mt-16 grid gap-6 md:grid-cols-2">
          {products.map((product) => (
            <Link
              key={product.name}
              to={product.href}
              className="group relative overflow-hidden rounded-2xl border border-line bg-white p-8 shadow-card transition hover:-translate-y-1 hover:shadow-hero"
            >
              <div
                className={`pointer-events-none absolute -right-16 -top-16 h-48 w-48 rounded-full bg-gradient-to-br ${product.accent} blur-2xl`}
              />

              <div className="relative">
                <div className="flex items-start justify-between">
                  <span className="inline-flex h-12 w-12 items-center justify-center rounded-xl bg-surface text-ink">
                    <product.icon className="h-5 w-5" />
                  </span>
                  <ArrowUpRight className="h-5 w-5 text-muted transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-brand" />
                </div>

                <p className="mt-6 text-xs font-semibold uppercase tracking-[0.12em] text-brand">
                  {product.tagline}
                </p>
                <h3 className="mt-2 font-heading text-2xl font-bold tracking-tight">
                  {product.name}
                </h3>
                <p className="mt-3 text-sm leading-relaxed text-muted">
                  {product.description}
                </p>

                <p className="mt-6 inline-flex items-center gap-1 text-sm font-semibold text-ink">
                  Learn more
                  <ArrowUpRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" />
                </p>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}
